name: Build FreeBSD Binary from Latest Official Source

on:
  workflow_dispatch:   # 手动触发，也可改为 push 或 schedule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout official picoshare repo
      uses: actions/checkout@v3
      with:
        repository: mtlynch/picoshare
        ref: main   
        fetch-depth: 1

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for FreeBSD amd64
      run: |
        GOOS=freebsd GOARCH=amd64 go build -o picoshare_freebsd ./cmd/picoshare

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: picoshare-freebsd-latest
        path: picoshare_freebsd
