name: Build & Release FreeBSD Binary

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (1.4.5)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone picoshare source
      run: |
        git clone --depth=1 https://github.com/mtlynch/picoshare.git
        cd picoshare
        git fetch --tags

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for FreeBSD
      run: |
        cd picoshare
        GOOS=freebsd GOARCH=amd64 go build -o picoshare_freebsd ./cmd/picoshare

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag }}
        name: Release ${{ github.event.inputs.tag }}
        files: picoshare/picoshare_freebsd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
