name: Build Picoshare for FreeBSD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone picoshare source
      run: |
        git clone --depth=1 https://github.com/mtlynch/picoshare.git

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build FreeBSD binary
      run: |
        cd picoshare
        GOOS=freebsd GOARCH=amd64 go build -o picoshare_freebsd ./cmd/picoshare

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: picoshare-freebsd
        path: picoshare/picoshare_freebsd
